#!/usr/bin/env node
/**
 * Rank the confirmed business areas by "bugs that came back" (ALP-7).
 *
 *   pnpm run audit:fragility:rank -- candidates   # 1. screen pairs for review
 *   pnpm run audit:fragility:rank                 # 2. rank reviewed pairs into the doc
 *
 * Step 1 reads `tmp/fragility/{repeats,github}.json` (from
 * `audit:fragility:collect` and `audit:fragility:signals`), drops the evidence
 * ALP-4's spot-checks found to be noise (see `screenCandidate`), and writes
 * `tmp/fragility/candidates.json`: every remaining pair with the areas
 * `areasForPair` suggests, for a person (or reviewing agent) to judge.
 *
 * Each judgement goes in the verdicts file (committed next to the ranking):
 * `{ "<earlier>-><later>": { verdict: "confirmed" | "rejected", area, reason } }`.
 * A confirmed pair is the same problem coming back — a re-break, a fix that
 * did not hold, or a second fix the first one should have covered — and it
 * counts once, in the one area the recurring problem belongs to.
 *
 * Step 2 ranks areas by confirmed pairs and rewrites the generated part of the
 * ranking doc (between the `fragility-rank` markers), listing each area's
 * repeats as chains with their links and signals. It refuses to run while a
 * candidate has no verdict, so the doc never ranks half-reviewed evidence.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

import { AREAS, areasForPair } from "./fragility-areas.mjs";
import { AUDIT_CUTOFF, INCIDENTAL_WORDING, MIN_REFIX_GAP_DAYS, REPO, issueUrl, pairKey } from "./fragility-lib.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const OUT_DIR = path.join(ROOT, "tmp/fragility");
const DEFAULT_DOC = "docs/audits/FRAGILITY_RANKING_2026-10.md";
const DEFAULT_VERDICTS = "docs/audits/FRAGILITY_RANKING_2026-10.verdicts.json";
const START = "<!-- fragility-rank:start (generated by scripts/audit/fragility-rank.mjs; edit verdicts, not this block) -->";
const END = "<!-- fragility-rank:end -->";
const DAY_MS = 86_400_000;

/** How each signal is named in the doc. */
export const SIGNAL_NAMES = {
  refix: "re-fix of the same issue",
  reopened: "reopened",
  mention: "text citation",
  revert: "revert",
  "code-history": "code-history overlap",
};

/**
 * Drop the evidence ALP-4 measured as noise, and the pair when nothing is left:
 * - a citation whose only repeat wording is "still";
 * - a re-fix of one issue landing under MIN_REFIX_GAP_DAYS after the first fix.
 *
 * @returns the entry with only its surviving evidence and signals, or null.
 */
export function screenCandidate(entry) {
  const gapDays = (Date.parse(entry.later.date) - Date.parse(entry.earlier.date)) / DAY_MS;
  const evidence = entry.evidence.filter((item) => {
    if (item.kind === "mention") return !INCIDENTAL_WORDING.test(item.wording ?? "");
    if (item.kind === "refix") return gapDays >= MIN_REFIX_GAP_DAYS;
    return true;
  });
  if (evidence.length === 0) return null;
  const signals = entry.signals.filter((signal) => evidence.some((item) => item.kind === signal));
  return { ...entry, evidence, signals };
}

/** Throw unless every verdict is well-formed and names a confirmed area. */
export function validateVerdicts(verdicts, areas = AREAS) {
  const ids = new Set(areas.map((area) => area.id));
  for (const [key, value] of Object.entries(verdicts)) {
    if (!["confirmed", "rejected"].includes(value.verdict)) throw new Error(`${key}: verdict must be confirmed or rejected, got ${value.verdict}`);
    if (value.verdict === "confirmed" && !ids.has(value.area)) throw new Error(`${key}: confirmed pair needs an area from AREAS, got ${value.area}`);
    if (!value.reason) throw new Error(`${key}: every verdict needs a reason`);
  }
}

/**
 * Group pairs into chains: pairs that share a fix (A → B, B → C) are one
 * problem coming back more than once. Chains and their links are oldest first.
 */
export function chainsOf(pairs) {
  const parent = new Map();
  const find = (key) => {
    while (parent.get(key) !== key) key = parent.get(key);
    return key;
  };
  for (const pair of pairs) {
    for (const key of [pair.earlier.key, pair.later.key]) if (!parent.has(key)) parent.set(key, key);
    parent.set(find(pair.later.key), find(pair.earlier.key));
  }
  const groups = new Map();
  for (const pair of pairs) {
    const root = find(pair.earlier.key);
    groups.set(root, [...(groups.get(root) ?? []), pair]);
  }
  const byDate = (a, b) => a.earlier.date.localeCompare(b.earlier.date) || a.later.date.localeCompare(b.later.date);
  return [...groups.values()].map((links) => links.sort(byDate)).sort((a, b) => byDate(a[0], b[0]));
}

/**
 * Rank areas by confirmed pairs (all history), then by pairs since the audit,
 * then by list order. Every area appears, including those with none.
 */
export function rankAreas(candidates, verdicts, areas = AREAS) {
  const rows = areas.map((area, index) => ({ ...area, index, confirmed: [], rejected: 0 }));
  const byId = new Map(rows.map((row) => [row.id, row]));
  for (const entry of candidates) {
    const verdict = verdicts[pairKey(entry.earlier.key, entry.later.key)];
    if (verdict?.verdict === "confirmed") byId.get(verdict.area).confirmed.push({ ...entry, reason: verdict.reason });
  }
  for (const row of rows) {
    row.sinceAudit = row.confirmed.filter((entry) => entry.later.date >= AUDIT_CUTOFF).length;
    row.chains = chainsOf(row.confirmed);
  }
  return rows.sort((a, b) => b.confirmed.length - a.confirmed.length || b.sinceAudit - a.sinceAudit || a.index - b.index);
}

/** `[PR #12](…) fix title (2026-05-02)`, or the commit or issue the side is. */
export function describeSide(side) {
  const date = side.date.slice(0, 10);
  const title = escapeMarkdown(truncate(side.title ?? "", 90));
  let label;
  if (side.pr) label = `PR #${side.pr}`;
  else if (side.issue) label = `issue #${side.issue}`;
  else label = `commit ${(side.commit ?? side.url.split("/").at(-1)).slice(0, 9)}`;
  const fixes = (side.issues ?? []).filter((number) => number !== side.pr).slice(0, 3);
  const fixesText = fixes.length > 0 ? ` (fixes ${fixes.map((number) => `[#${number}](${issueUrl(number)})`).join(", ")})` : "";
  return `[${label}](${side.url})${fixesText} ${title} (${date})`;
}

function truncate(text, max) {
  const flat = text.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat;
}

function escapeMarkdown(text) {
  return text.replace(/([\\`*_[\]<>|])/g, "\\$1");
}

function describeSignals(entry) {
  const seen = new Set();
  const parts = [];
  for (const item of entry.evidence) {
    if (seen.has(item.kind)) continue;
    seen.add(item.kind);
    parts.push(`[${SIGNAL_NAMES[item.kind]}](${item.url})`);
  }
  return parts.join(", ");
}

/** The generated block: ranking table, then each area's chains. */
export function renderRanking(rows, { reviewed, rejected, screenedOut, total }) {
  const lines = [START, "", "## Ranking", ""];
  lines.push(
    `Ranked by confirmed repeat pairs across all history (since 2026-04-03). "Since 8 Aug" counts the confirmed pairs whose later side landed on or after ${AUDIT_CUTOFF}.`,
    "",
    "| Rank | Area | Confirmed repeats | Since 8 Aug | Chains |",
    "| --: | --- | --: | --: | --: |",
  );
  rows.forEach((row, index) => {
    lines.push(`| ${index + 1} | [${row.name}](#${anchorFor(index + 1, row)}) | ${row.confirmed.length} | ${row.sinceAudit} | ${row.chains.length} |`);
  });
  lines.push(
    "",
    `${total} candidate pairs from the signals; ${screenedOut} screened out as known noise; ${reviewed} reviewed by hand: ${reviewed - rejected} confirmed, ${rejected} rejected.`,
    "",
    "## Repeats by area",
    "",
    "Each chain is one problem coming back: every line is an earlier fix → the later re-fix or re-break, the signals that found it (each linked to its evidence), and why the pair was confirmed.",
  );
  rows.forEach((row, index) => {
    lines.push("", `### ${headingFor(index + 1, row)}`, "");
    if (row.chains.length === 0) {
      lines.push("No confirmed repeats.");
      return;
    }
    row.chains.forEach((chain, chainIndex) => {
      const fixes = new Set(chain.flatMap((pair) => [pair.earlier.key, pair.later.key])).size;
      lines.push(`${chainIndex + 1}. Chain of ${fixes} fixes:`);
      for (const pair of chain) {
        lines.push(`   - ${describeSide(pair.earlier)} → ${describeSide(pair.later)}`);
        lines.push(`     — ${describeSignals(pair)}. ${escapeMarkdown(pair.reason)}`);
      }
    });
  });
  lines.push("", END);
  return lines.join("\n");
}

function headingFor(rank, row) {
  const since = `${row.sinceAudit} since 8 Aug`;
  return `${rank}. ${row.name} — ${row.confirmed.length} confirmed, ${since}`;
}

/** GitHub's heading anchor: lower case, punctuation dropped, spaces to hyphens. */
function anchorFor(rank, row) {
  return headingFor(rank, row)
    .toLowerCase()
    .replace(/[^\p{L}\p{N} -]/gu, "")
    .replace(/ /g, "-");
}

/** Replace the generated block in `doc`, keeping the hand-written text around it. */
export function replaceGenerated(doc, block) {
  const start = doc.indexOf(START.slice(0, 26));
  const end = doc.indexOf(END);
  if (start === -1 || end === -1) throw new Error("ranking doc has no fragility-rank markers");
  return `${doc.slice(0, start)}${block}${doc.slice(end + END.length)}`;
}

function readJson(file) {
  if (!existsSync(file)) {
    console.error(`${path.relative(ROOT, file)} is missing. Run audit:fragility:collect and audit:fragility:signals first.`);
    process.exit(2);
  }
  return JSON.parse(readFileSync(file, "utf8"));
}

function option(name, fallback) {
  const index = process.argv.indexOf(`--${name}`);
  return path.resolve(ROOT, index === -1 ? fallback : process.argv[index + 1]);
}

function screened() {
  const { repeats } = readJson(path.join(OUT_DIR, "repeats.json"));
  return { total: repeats.length, candidates: repeats.map(screenCandidate).filter(Boolean) };
}

function writeCandidates() {
  const { total, candidates } = screened();
  const github = readJson(path.join(OUT_DIR, "github.json"));
  const labelsByNumber = new Map(github.issues.map((issue) => [issue.number, issue.labels]));
  const out = candidates.map((entry) => ({
    key: pairKey(entry.earlier.key, entry.later.key),
    suggestedAreas: areasForPair(entry, labelsByNumber),
    ...entry,
  }));
  writeFileSync(path.join(OUT_DIR, "candidates.json"), `${JSON.stringify({ builtAt: new Date().toISOString(), repo: REPO, candidates: out }, null, 1)}\n`);
  console.error(`wrote tmp/fragility/candidates.json: ${out.length} of ${total} pairs survive screening`);
}

function writeRanking() {
  const { total, candidates } = screened();
  const verdictsFile = option("verdicts", DEFAULT_VERDICTS);
  const verdicts = readJson(verdictsFile);
  validateVerdicts(verdicts);
  const missing = candidates.map((entry) => pairKey(entry.earlier.key, entry.later.key)).filter((key) => !verdicts[key]);
  if (missing.length > 0) {
    console.error(`${missing.length} candidate pairs have no verdict in ${path.relative(ROOT, verdictsFile)}, e.g. ${missing.slice(0, 5).join(", ")}`);
    process.exit(1);
  }
  const keys = new Set(candidates.map((entry) => pairKey(entry.earlier.key, entry.later.key)));
  const rejected = Object.entries(verdicts).filter(([key, value]) => keys.has(key) && value.verdict === "rejected").length;
  const rows = rankAreas(candidates, verdicts);
  const docFile = option("doc", DEFAULT_DOC);
  const block = renderRanking(rows, { reviewed: candidates.length, rejected, screenedOut: total - candidates.length, total });
  writeFileSync(docFile, replaceGenerated(readFileSync(docFile, "utf8"), block));
  console.error(`ranked ${rows.length} areas into ${path.relative(ROOT, docFile)}`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  if (process.argv.includes("candidates")) writeCandidates();
  else writeRanking();
}
