/*
 * Golden-value generator (#2187, epic #2181 P1).
 *
 * Emits src/lib/theme/__tests__/theme-goldens.json — the exact substrate hexes for
 * both migrated seed sets (default + tokoroa) × both modes, plus the fixed kiosk
 * (A5). The golden-value test pins these; a ±1/255 float wiggle becomes a test diff,
 * not a silent ship.
 *
 * J6/F5 — MUST be run inside the production image base so the pinned values match
 * what CI verifies. Exact command (also in the PR body):
 *
 *   docker run --rm -v "$PWD":/repo -w /repo node:24.17-alpine \
 *     sh -c "npm ci --no-audit --no-fund && npx tsx scripts/theme/generate-goldens.ts"
 *
 * Regenerating on the local Node 22 is FORBIDDEN for the committed golden — a float
 * wiggle would bake a v22 value into a v24-verified golden. A local run is only for
 * a provisional check and must be labelled PROVISIONAL-NODE22.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  buildThemeSubstrate,
  buildKioskTheme,
  a2ComputedPick,
  a4SolidForeground,
  HUE_SCALES,
} from "../../src/lib/theme/theme-substrate";
import { SEED_SETS } from "../../src/lib/theme/__tests__/reference-seed-sets";
import { must } from "../../src/lib/indexed-access";

function scaleHexes(theme: ReturnType<typeof buildThemeSubstrate>) {
  const out: Record<string, string[]> = {};
  for (const [name, s] of Object.entries(theme.scales)) out[name] = s.hex;
  return out;
}

const goldens: Record<string, unknown> = {
  note: "Generated by scripts/theme/generate-goldens.ts. DO NOT EDIT BY HAND. Regenerate inside node:24.17-alpine (see header). Values pin the full substrate.",
  nodeMajor: process.versions.node.split(".")[0],
  seeds: SEED_SETS,
  themes: {},
};

const themes: Record<string, unknown> = {};
for (const seedName of Object.keys(SEED_SETS) as Array<keyof typeof SEED_SETS>) {
  const light = buildThemeSubstrate(SEED_SETS[seedName], "light");
  const dark = buildThemeSubstrate(SEED_SETS[seedName], "dark");
  // A fixed 12-step neutral ramp, same guarantee as buildKioskTheme's own
  // light-neutral-12 (src/lib/theme/theme-substrate.ts).
  const lightN12 = must(light.neutralHex[11], "generate-goldens: light neutral ramp has no step 12");
  // A4 solid-fg for each hue scale, both modes, using this seed set's light neutral-12.
  const a4 = (t: typeof light) => {
    const o: Record<string, { step9: string; step10: string }> = {};
    for (const name of HUE_SCALES) {
      // buildThemeSubstrate populates `scales` from this same HUE_SCALES list
      // (plus "neutral"), so every name here is a guaranteed key.
      const s = must(t.scales[name], `generate-goldens: theme has no "${name}" scale`);
      const step9 = must(s.hex[8], `generate-goldens: "${name}" scale has no step 9`);
      const step10 = must(s.hex[9], `generate-goldens: "${name}" scale has no step 10`);
      o[name] = {
        step9: a4SolidForeground(step9, s.generatorContrast as string, lightN12).pick,
        step10: a4SolidForeground(step10, s.generatorContrast as string, lightN12).pick,
      };
    }
    return o;
  };
  themes[seedName] = {
    light: { scales: scaleHexes(light), neutralAlpha: light.neutralAlpha, a2Computed: a2ComputedPick(light.neutralHex), a4SolidFg: a4(light) },
    dark: { scales: scaleHexes(dark), neutralAlpha: dark.neutralAlpha, a2Computed: a2ComputedPick(dark.neutralHex), a4SolidFg: a4(dark) },
  };
}

const { theme: kiosk, lightNeutral12: kioskLN12 } = buildKioskTheme();
// buildKioskTheme sets "accent" itself, so this key is guaranteed present.
const kioskAccent = must(kiosk.scales.accent, "generate-goldens: kiosk theme has no accent scale");
const kioskAccentStep9 = must(kioskAccent.hex[8], "generate-goldens: kiosk accent scale has no step 9");
const kioskAccentStep10 = must(kioskAccent.hex[9], "generate-goldens: kiosk accent scale has no step 10");
themes.kiosk = {
  dark: {
    scales: scaleHexes(kiosk),
    neutralAlpha: kiosk.neutralAlpha,
    a2Computed: a2ComputedPick(kiosk.neutralHex),
    a4SolidFg: {
      accent: {
        step9: a4SolidForeground(kioskAccentStep9, kioskAccent.generatorContrast as string, kioskLN12).pick,
        step10: a4SolidForeground(kioskAccentStep10, kioskAccent.generatorContrast as string, kioskLN12).pick,
      },
    },
  },
};
goldens.themes = themes;

const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "src", "lib", "theme", "__tests__", "theme-goldens.json");
writeFileSync(outPath, JSON.stringify(goldens, null, 2) + "\n");
console.log(`Wrote ${outPath} on Node ${process.versions.node}`);
