/**
 * Rendered-email equivalence gate (#2689).
 *
 * The #2689 split moved every template out of a 5,000-line monolith into one
 * module per message family. Inline email CSS is order-dependent, so a move
 * that reads as mechanical in the diff can still change the cascade a mail
 * client applies. The owner's rule for that split is that rendered output stays
 * byte-for-byte invariant and that ANY diff is a blocking finding, so this test
 * pins the complete rendered body of every template — not a fragment, not a
 * function name — against committed hashes.
 *
 * It is a permanent gate, not a one-off proof: the next structural move must
 * not be able to change output silently either.
 *
 * WHEN IT FAILS. Commit the real change first, record its exact head, and use
 * a separate temporary worktree at the comparison ref; never use the shared
 * stash stack or rewrite the worktree being tested. Give each worktree its own
 * physical dependencies per docs/agents/CODEX_WORKFLOW.md, then run this in
 * each one (with different absolute dump directories):
 *
 *   $env:EMAIL_RENDER_DUMP = "C:\\temp\\email-render-before"
 *   pnpm test src/lib/__tests__/email-render-equivalence.test.ts
 *   Remove-Item Env:EMAIL_RENDER_DUMP
 *
 * Use `git diff --no-index -- <before-directory> <after-directory>` to compare
 * the two complete-body dumps.
 *
 * If — and only if — the change to the output is intended and reviewed, rewrite
 * the pins with UPDATE_EMAIL_RENDER_PINS=1. That mode always fails the run, so
 * a regenerated pin file can never be mistaken for a passing gate.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it, vi } from "vitest";

// The palette is read per render from the club (Site Style) theme and IS part
// of the output. Pin it to the site default — the same values a cold cache
// already uses — so the corpus is deterministic and never reaches the database.
vi.mock("@/lib/club-theme", () => ({
  getWebsiteThemeRenderState: async () => {
    const { DEFAULT_CLUB_THEME_VALUES } = await import("@/lib/club-theme-schema");
    return { values: DEFAULT_CLUB_THEME_VALUES, css: "" };
  },
}));

import { EMAIL_TEMPLATE_DEFINITIONS } from "@/lib/email-message-registry";
import {
  EMAIL_RENDER_CASES,
  type EmailRenderCase,
} from "@/lib/__tests__/support/email-render-cases";
import {
  assertUniqueEmailTemplateExportNames,
  readEmailTemplateModuleExports,
  REGISTRY_KEY_RENDERERS,
  REGISTRY_KEYS_WITHOUT_A_TEMPLATE_FUNCTION,
} from "@/lib/__tests__/support/email-render-coverage";

const PINS_PATH = path.join(
  __dirname,
  "support",
  "email-render-pins.txt",
);

const PINS_HEADER = [
  "# Rendered-email pins (#2689). One line per case: <id> <TAB> <bytes> <TAB> sha256.",
  "# Generated by src/lib/__tests__/email-render-equivalence.test.ts.",
  "# Regenerate ONLY for a reviewed, intended output change:",
  '#   $env:UPDATE_EMAIL_RENDER_PINS = "1"',
  "#   pnpm test src/lib/__tests__/email-render-equivalence.test.ts",
  "#   Remove-Item Env:UPDATE_EMAIL_RENDER_PINS",
].join("\n");

function digest(body: string): { bytes: number; sha256: string } {
  const buffer = Buffer.from(body, "utf8");
  return {
    bytes: buffer.byteLength,
    sha256: createHash("sha256").update(buffer).digest("hex"),
  };
}

function assertUniqueIds(ids: Iterable<string>, source: string): void {
  const seen = new Set<string>();
  for (const id of ids) {
    if (seen.has(id)) {
      throw new Error(
        `Duplicate ${source} id "${id}". The gate refuses to let a later entry ` +
          "overwrite the first and create a false green.",
      );
    }
    seen.add(id);
  }
}

function renderAll(
  cases: readonly EmailRenderCase[] = EMAIL_RENDER_CASES,
): Map<string, { bytes: number; sha256: string }> {
  // Validate the corpus before rendering anything. Apart from preventing a Map
  // overwrite, this keeps a duplicate case's render side effects out of a run
  // that is invalid by construction.
  assertUniqueIds(
    cases.map((testCase) => testCase.id),
    "render-case",
  );

  const rendered = new Map<string, { bytes: number; sha256: string }>();
  const dumpDir = process.env.EMAIL_RENDER_DUMP;
  if (dumpDir) mkdirSync(dumpDir, { recursive: true });

  for (const testCase of cases) {
    const body = testCase.render();
    if (dumpDir) {
      writeFileSync(
        path.join(dumpDir, `${testCase.id.replace(/[^A-Za-z0-9_.-]/g, "_")}.txt`),
        body,
        "utf8",
      );
    }
    rendered.set(testCase.id, digest(body));
  }
  return rendered;
}

function readPins(
  raw: string = readFileSync(PINS_PATH, "utf8"),
): Map<string, { bytes: number; sha256: string }> {
  const pins = new Map<string, { bytes: number; sha256: string }>();
  for (const rawLine of raw.split("\n")) {
    // Belt and braces with the `eol=lf` pin in .gitattributes: a stray CR would
    // otherwise ride on the sha256 field and fail every template at once.
    const line = rawLine.replace(/\r$/, "");
    if (!line.trim() || line.startsWith("#")) continue;
    const [id, bytes, sha256] = line.split("\t");
    if (!id || !bytes || !sha256) {
      throw new Error(`Malformed pin line in email-render-pins.txt: ${line}`);
    }
    if (pins.has(id)) {
      throw new Error(
        `Duplicate pin id "${id}" in email-render-pins.txt. The gate refuses ` +
          "to let a later pin overwrite the first and create a false green.",
      );
    }
    pins.set(id, { bytes: Number(bytes), sha256 });
  }
  return pins;
}

function writePins(rendered: Map<string, { bytes: number; sha256: string }>) {
  const lines = [...rendered.entries()].map(
    ([id, { bytes, sha256 }]) => `${id}\t${bytes}\t${sha256}`,
  );
  writeFileSync(PINS_PATH, `${PINS_HEADER}\n${lines.join("\n")}\n`, "utf8");
}

describe("rendered-email equivalence (#2689)", () => {
  const rendered = renderAll();

  if (process.env.UPDATE_EMAIL_RENDER_PINS === "1") {
    it("regenerated the pins and therefore FAILS this run", () => {
      writePins(rendered);
      throw new Error(
        `Rewrote ${PINS_PATH} with ${rendered.size} pins. This mode always fails: ` +
          "review the diff, confirm the output change was intended, then re-run without " +
          "UPDATE_EMAIL_RENDER_PINS.",
      );
    });
    return;
  }

  it("has a committed pin file", () => {
    expect(
      existsSync(PINS_PATH),
      `${PINS_PATH} is missing. Without it this gate proves nothing.`,
    ).toBe(true);
  });

  it("fails closed on duplicate render-case ids before rendering or overwriting", () => {
    let renderCalls = 0;
    const duplicateCases: EmailRenderCase[] = [
      {
        id: "duplicate-case",
        fn: "firstRenderer",
        render: () => {
          renderCalls += 1;
          return "first";
        },
      },
      {
        id: "duplicate-case",
        fn: "secondRenderer",
        render: () => {
          renderCalls += 1;
          return "second";
        },
      },
    ];

    expect(() => renderAll(duplicateCases)).toThrowError(
      'Duplicate render-case id "duplicate-case"',
    );
    expect(renderCalls).toBe(0);
  });

  it("fails closed on duplicate pin ids before a later pin can overwrite", () => {
    const firstHash = "a".repeat(64);
    const secondHash = "b".repeat(64);
    const duplicatePins =
      `duplicate-pin\t1\t${firstHash}\n` +
      `duplicate-pin\t2\t${secondHash}\n`;

    expect(() => readPins(duplicatePins)).toThrowError(
      'Duplicate pin id "duplicate-pin"',
    );
  });

  it("pins exactly the cases that exist — no case silently added or dropped", () => {
    const pins = readPins();
    const renderedIds = [...rendered.keys()].sort();
    const pinnedIds = [...pins.keys()].sort();
    expect(pinnedIds).toEqual(renderedIds);
  });

  it("renders every template byte-for-byte identically to its pin", () => {
    const pins = readPins();
    const drifted: string[] = [];
    for (const [id, actual] of rendered) {
      const pinned = pins.get(id);
      if (!pinned) continue; // covered by the id-set test above
      if (pinned.sha256 !== actual.sha256 || pinned.bytes !== actual.bytes) {
        drifted.push(
          `${id}: pinned ${pinned.bytes}B ${pinned.sha256.slice(0, 12)} -> rendered ` +
            `${actual.bytes}B ${actual.sha256.slice(0, 12)}`,
        );
      }
    }
    expect(
      drifted,
      "Rendered email output changed. Under #2689 this is a BLOCKING finding, not an " +
        "expectation to update. Re-read the module docblock for how to dump and diff " +
        "the bodies:\n" +
        drifted.join("\n"),
    ).toEqual([]);
  });

  // Reads the module DIRECTORY rather than a list, because a list is a second
  // place to forget: with the module names written out by hand, a whole new
  // family module could be added and stay invisible to this gate.
  it("covers every exported render function in every template module", async () => {
    const moduleExports = await readEmailTemplateModuleExports();
    expect(Object.keys(moduleExports).length).toBeGreaterThan(0);

    const coveredFns = new Set(EMAIL_RENDER_CASES.map((c: EmailRenderCase) => c.fn));
    const uncovered: string[] = [];
    for (const [moduleName, exportNames] of Object.entries(moduleExports)) {
      for (const exportName of exportNames) {
        if (!coveredFns.has(exportName)) uncovered.push(`${moduleName}.${exportName}`);
      }
    }
    expect(
      uncovered,
      "These exported render functions have no case in email-render-cases.ts, so a " +
        "structural move could change their output unnoticed:\n" + uncovered.join("\n"),
    ).toEqual([]);
  });

  it("rejects duplicate bare render-function names across template modules", () => {
    expect(() =>
      assertUniqueEmailTemplateExportNames({
        account: ["passwordResetTemplate"],
        "unregistered-family": ["passwordResetTemplate"],
      }),
    ).toThrowError(
      'Duplicate email-template function export "passwordResetTemplate" in ' +
        'modules "account" and "unregistered-family"',
    );
  });

  it("covers every production template the message registry registers", () => {
    const coveredFns = new Set(EMAIL_RENDER_CASES.map((c: EmailRenderCase) => c.fn));
    const unmapped: string[] = [];
    const uncovered: string[] = [];
    for (const definition of EMAIL_TEMPLATE_DEFINITIONS) {
      if (REGISTRY_KEYS_WITHOUT_A_TEMPLATE_FUNCTION.has(definition.key)) continue;
      const renderer = REGISTRY_KEY_RENDERERS[definition.key];
      if (!renderer) {
        unmapped.push(definition.key);
        continue;
      }
      if (!coveredFns.has(renderer)) uncovered.push(`${definition.key} -> ${renderer}`);
    }
    expect(
      unmapped,
      "Registry template keys with no mapped render function. Add the mapping in " +
        "email-render-coverage.ts (or record why the key has no template function):\n" +
        unmapped.join("\n"),
    ).toEqual([]);
    expect(
      uncovered,
      "Registry template keys whose render function has no render case:\n" +
        uncovered.join("\n"),
    ).toEqual([]);
  });

  it("renders deterministically — the same case twice produces the same bytes", () => {
    const second = renderAll();
    for (const [id, first] of rendered) {
      expect(second.get(id), `${id} rendered differently on a second call`).toEqual(
        first,
      );
    }
  });
});
